# Generated by Django 4.1.6 on 2023-02-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="xp",
            field=models.IntegerField(default=0),
        ),
    ]
