# Generated by Django 4.1.6 on 2023-02-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='radius',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='buildingName',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='lat',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='long',
            new_name='name',
        ),
    ]
