# Generated by Django 4.1.6 on 2023-03-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaderboard",
            old_name="quiz_count",
            new_name="numGamesPlayed",
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="profilePictureIndex",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="timesPlayedCrossword",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="timesPlayedHangman",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="timesPlayedTicTacToe",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="timesPlayedTrivia",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="timesPlayedWordSearch",
            field=models.IntegerField(default=0),
        ),
    ]
