# flake8: noqa

# Generated by Django 4.1.6 on 2023-03-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
                ('hint', models.CharField(max_length=200)),
                ('fact', models.CharField(max_length=200)),
            ],
        ),
    ]
